# Generated by Django 3.0.5 on 2020-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0002_digital_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='team')),
                ('position', models.CharField(max_length=20)),
                ('facebook', models.URLField(blank=True, max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, max_length=50, null=True)),
                ('github', models.URLField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=50, null=True)),
                ('gmail', models.URLField(blank=True, max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='digital',
            name='link',
        ),
    ]
