# Generated by Django 3.0.5 on 2020-04-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0004_moments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moments',
            new_name='Moment',
        ),
    ]
