# Generated by Django 3.0.5 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0007_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='notice',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='notice'),
        ),
    ]
