# Generated by Django 3.0.5 on 2020-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0008_auto_20200429_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
