# Generated by Django 3.0.5 on 2020-04-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0010_auto_20200429_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='img4',
        ),
    ]
