# Generated by Django 3.0.5 on 2020-04-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0011_auto_20200429_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='img1',
            new_name='img',
        ),
    ]
