# Generated by Django 3.0.7 on 2020-06-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0013_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
