# Generated by Django 3.0.7 on 2020-06-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAC', '0014_winner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='name',
            new_name='competition_name',
        ),
    ]
